# Generated by Django 4.2 on 2026-02-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_warned',
            field=models.BooleanField(default=False),
        ),
    ]
