# Generated by Django 4.2 on 2026-02-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email_verification_token_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='car_photo_front',
            field=models.ImageField(blank=True, null=True, upload_to='driver_documents/car_photos/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='car_photo_side',
            field=models.ImageField(blank=True, null=True, upload_to='driver_documents/car_photos/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='car_registration',
            field=models.ImageField(blank=True, null=True, upload_to='driver_documents/registrations/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='documents_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='driver_license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_documents/licenses/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='national_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_documents/national_ids/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
