# Generated by Django 4.2 on 2026-02-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_code_created_at_user_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('driver', 'Driver')], max_length=20),
        ),
    ]
