# Generated by Django 4.2 on 2026-02-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
