# Generated by Django 4.2 on 2026-02-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='car_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ride_cars/'),
        ),
    ]
